### ISSUE TITLE
pipenv lock edge case problem in setup.py

### ISSUE THREAD

**Issue by daegontaven** [xolox/python-coloredlogs#48] opened 2018-03-08 06:31 UTC
It appears the setup.py file is configured incorrectly and causes problems when trying to `pipenv lock`. It is better to return a list of strings with the appropriate format as recommended by the setuptools documentation.

https://github.com/xolox/python-coloredlogs/blob/399af2a2199629c613b64c92d9d6c2462973ff86/setup.py#L135-L137

This issue describes the problem in detail: https://github.com/pypa/pipenv/issues/1578#issuecomment-371277898

This is is not very easy to reproduce on many machines, but is apparently a very common issue that pops up in pipenv.

**Comment by xolox** [comment] 2018-03-08 12:18
Thinking out loud: It's weird that coloredlogs is being used by thousands and no one has ever reported this. Must be a recent change then? And it doesn't break setuptools, nor pip, but it does break pipenv?

A more general observation: Declaring conditional dependencies in Python has turned into an absolute nightmare of backwards incompatibility :cry:. I can point to a dozen commits in various projects of mine where multiple strategies were evaluated and disregarded because they broke compatibility somewhere.

Back to this issue: I'm willing to entertain the thought of opening up this can of worms again, if the end result is going to be better for it, but I'm hesitant because I'm expecting it to cause breakage for users stuck in old(er) environments (e.g. with older versions of setuptools installed).

Anyone with an informed opinion on the matter is welcome to enlighten me :wink:.

**Comment by xolox** [comment] 2018-04-26 16:14
I'm going to close this issue because I think "it resolved itself" (via upstream bug fixes in pipenv).

**More details:**

- Similar problems were reported in xolox/python-humanfriendly#25 and when I investigated those I found that I could no longer reproduce the reported problem based on the newest version of pipenv (11.10.0).
- Then I got curious so I went looking for the [pipenv changelog](https://github.com/pypa/pipenv/blob/master/HISTORY.txt) and found that it lists various improvements to marker support in recent releases.

So I suggest you give the latest version of pipenv a try, because it works for me (TM) :wink:.

**Closed by xolox** 2018-04-26 16:15 UTC
