### ISSUE TITLE
do not works with setting explicit logger

### ISSUE THREAD

**Issue by vitaly-zdanevich** [xolox/python-coloredlogs#24] opened 2016-12-26 06:18 UTC
This works on the app with few lines of codes:
`coloredlogs.install(logger=logger, level=logging.DEBUG, fmt=fmt_term, datefmt=datefmt)`
but at my big app setting explicit logger looks like disabling coloring at all;

this color my logs - but for all libraries - that I do not need:
`coloredlogs.install(fmt=fmt_term, datefmt=datefmt)`

**Comment by xolox** [comment] 2017-03-13 18:51
Hi Vitaly and thanks for the feedback.

> but at my big app setting explicit logger looks like disabling coloring at all

I believe this was caused by a bug which was recently fixed. I've since released coloredlogs 6.0 which contains the fix, please give it a try. I'm closing this issue now, but feel free to reopen it if you don't agree.

**Closed by xolox** 2017-03-13 18:51 UTC

**Comment by xingheng** [comment] 2019-11-17 10:04
Encountered the same issue in 10.0, too.

**Comment by xingheng** [comment] 2019-11-17 10:11
Found it! If I enable the `logging.basicConfig(format=_FORMAT)` below, then all the dependency libraries's log show up.

Is it on purpose?

```

import coloredlogs, logging

_FORMAT = '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
# logging.basicConfig(format=_FORMAT)

def getLogger(name):
    '''Custom logger.'''

    logger = logging.getLogger(name)
    # logger.setLevel(logging.DEBUG)
    coloredlogs.install(level='DEBUG', logger=logger, fmt=_FORMAT)

    return logger
```
