### ISSUE TITLE
Problem when use coloredlogs with other libraries.

### ISSUE THREAD

**Issue by LiGhT1EsS** [xolox/python-coloredlogs#18] opened 2016-07-26 16:25 UTC
When I use selenium+phantomjs and coloredlogs, I found all log will output to the console, include selenuim's log. I just want show my log. How can I close the other logs?

This is my code:

``` python
FIELD_STYLES = dict(
    asctime=dict(color='green'),
    hostname=dict(color='magenta'),
    levelname=dict(color='green', bold=coloredlogs.CAN_USE_BOLD_FONT),
    filename=dict(color='magenta'),
    name=dict(color='blue'),
    threadName=dict(color='green')
)

LEVEL_STYLES = dict(
    debug=dict(color='green'),
    info=dict(color='cyan'),
    verbose=dict(color='blue'),
    warning=dict(color='yellow'),
    error=dict(color='red'),
    critical=dict(color='red', bold=coloredlogs.CAN_USE_BOLD_FONT)
)
logger = logging.getLogger("ProjectName")

cf = ConfigParser.ConfigParser()
cf.read("config.ini")
if cf.has_option("ProjectName", "debug") and cf.get("ProjectName", "debug") == "On":
    level = "DEBUG"
else:
    level = "INFO"

coloredlogs.install(
    level=level,
    fmt="[%(levelname)s] [(%(threadName)s)] [%(asctime)s] [%(filename)s:%(lineno)d] %(message)s",
    datefmt="%H:%M:%S",
    level_styles=LEVEL_STYLES,
    field_styles=FIELD_STYLES,
)
```

And I write log like this:

``` python
logger.debug("debug information")
```

And the output like this:

``` shell
[INFO] [(MainThread)] [00:06:46] [WebSpider.py:74] initial web spider phantomjs process pool...
[DEBUG] [(MainThread)] [00:06:51] [remote_connection.py:415] POST http://127.0.0.1:11225/wd/hub/session {"requiredCapabilities": {}, "desiredCapabilities": {"javascriptEnabled": true, "phantomjs.page.settings.resourceTimeout": 10, "phantomjs.page.settings.loadImages": false, "platform": "ANY", "browserName": "phantomjs", "version": ""}}
[DEBUG] [(MainThread)] [00:06:51] [remote_connection.py:510] Finished Request
[INFO] [(MainThread)] [00:06:51] [WebSpider.py:85] 25.00% finished.
```

The "remote_connection.py:510" isn't my log, maybe it create by selenium or phantomjs.

After read some docs, I found the coloredlogs.install() function has a param called logger, if it None, it will set to the root logger, so I pass my logger to it, like this below:

``` python
coloredlogs.install(
    level=level,
    logger=logger,
    fmt="[%(levelname)s] [(%(threadName)s)] [%(asctime)s] [%(filename)s:%(lineno)d] %(message)s",
    datefmt="%H:%M:%S",
    level_styles=LEVEL_STYLES,
    field_styles=FIELD_STYLES,
)
```

But this time, there is no log output to console, so I pass a stream to this function, "stream=sys.stdout", also no output.

Did I do something wrong?

**Comment by LiGhT1EsS** [comment] 2016-07-26 16:27
My environment is Win10 + Python 2.7.11

**Comment by icyblade** [comment] 2016-10-20 06:56
Same thing happened for TensorFlow, maybe coloredlogs changed something global.
I'm trying to figure it out.

**Comment by RedCraig** [comment] 2016-11-16 16:12
I'm having a bit of difficulty with this actually. I have a feeling I'm misunderstanding how to set up a logger instance for coloredlogs correctly.

Using the python logging howto example, and adding coloredlogs:
```python
import logging

# create logger
logger = logging.getLogger('simple_example')
logger.setLevel(logging.DEBUG)
ch = logging.StreamHandler()
ch.setLevel(logging.DEBUG)
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
ch.setFormatter(formatter)
logger.addHandler(ch)

# test output
logger.debug('debug message')
logger.info('info message')
logger.warn('warn message')
logger.error('error message')
logger.critical('critical message')

import coloredlogs
coloredlogs.install(level='DEBUG', logger=logger)
logger.debug('debug message')
logger.info('info message')
logger.warn('warn message')
logger.error('error message')
logger.critical('critical message')
```
outputs:
```
2016-11-16 16:06:53,942 - simple_example - DEBUG - debug message
2016-11-16 16:06:53,942 - simple_example - INFO - info message
2016-11-16 16:06:53,942 - simple_example - WARNING - warn message
2016-11-16 16:06:53,942 - simple_example - ERROR - error message
2016-11-16 16:06:53,942 - simple_example - CRITICAL - critical message
2016-11-16 16:06:53 <hostname> simple_example[63650] WARNING warn message
2016-11-16 16:06:53 <hostname> simple_example[63650] ERROR error message
2016-11-16 16:06:53 <hostname> simple_example[63650] CRITICAL critical message
```

The streamhandler correctly outputs debug level logs, but after coloredlogs is installed the log level is set to warning and info/debug logs are not emitted.

How can pass in a configured logger to coloredlogs (so that other libraries do log via root logger) and set the coloredlogs level to info/debug?

Thanks for any help.

**Comment by xolox** [comment] 2017-03-13 18:46
Hi everyone and thanks for the feedback. In the opening post to this issue @LiGhT1EsS mentioned:

> Did I do something wrong?

You correctly understood the documentation (and my intention for how coloredlogs should work) but a bug prevented things from working correctly. A few days ago I released coloredlogs 6.0 which should fix this bug. Please try out the latest version, I believe it resolves your problem.

By the way I've also updated the example in the readme to show how to install logging for one specific logger as you initially desired.

Later on @RedCraig mentioned:

> I'm having a bit of difficulty with this actually. I have a feeling I'm misunderstanding how to set up a logger instance for coloredlogs correctly.

Sorry for the confusion! This was due to the previously mentioned bug. I believe that coloredlogs 6.0 should end this confusion, both by fixing the bug and improving the documentation.

I'm closing this issue now because I believe that the problems reported here are resolved. If someone disagrees, feel free to reopen this issue or open a new one.

**Closed by xolox** 2017-03-13 18:46 UTC

**Comment by jacobcxdev** [comment] 2021-02-25 16:22
Forgive me if I'm wrong, but it appears that this issue is occurring for me with the latest version of coloredlogs.

When using Python's logging module, I can simply use the following code to set the logging level of my logger to `DEBUG`:
```py
self.logger.setLevel(logging.DEBUG)
```

However, when using coloredlogs, the following code sets the log level on the root logger instead of `self.logger`:
```py
coloredlogs.install(level=logging.DEBUG, logger=self.logger)
```

One workaround is to do this, but it's not particularly clean:
```py
coloredlogs.install(level=logging.DEBUG, logger=self.logger)
logging.getLogger().setLevel(logging.WARNING)
```

After a little research, I noticed that the logger gets set to the root logger here:
https://github.com/xolox/python-coloredlogs/blob/18510692e821070e91ea988415db39b6903469d5/coloredlogs/__init__.py#L413

This made me wonder whether I was adding a handler to the root logger anywhere else, leading me to discover that if I call `logging.basicConfig()` elsewhere for any reason (e.g. to set a format for the root logger) it will cause the above issue.

Is this expected behaviour?

**Comment by maresb** [comment] 2023-03-06 13:22
@jacobcxdev, I'm also running into this. In my case it appears that running `coloredlogs.install` first and `logging.basicConfig` second is okay, but the other way around results in the root logger level being changed.

Following your analysis, I looked into the source of `replace_handler`, and I see that by setting the `reconfigure=False` parameter in `coloredlogs.install` prevents `replace_handler` from switching to the root logger.

The [API docs](https://coloredlogs.readthedocs.io/en/latest/api.html#coloredlogs.install) say,

> If reconfigure is [True](https://docs.python.org/3/library/constants.html#True) (it is by default) and an existing [StreamHandler](https://docs.python.org/3/library/logging.handlers.html#logging.StreamHandler) is found that is connected to either [stdout](https://docs.python.org/3/library/sys.html#sys.stdout) or [stderr](https://docs.python.org/3/library/sys.html#sys.stderr) the handler will be removed. This means that first calling [logging.basicConfig()](https://docs.python.org/3/library/logging.html#logging.basicConfig) and then calling [coloredlogs.install()](https://coloredlogs.readthedocs.io/en/latest/api.html#coloredlogs.install) will replace the stream handler instead of adding a duplicate stream handler. If reconfigure is [False](https://docs.python.org/3/library/constants.html#False) and an existing handler is found no further steps are taken (to avoid installing a duplicate stream handler).

I still can't say I understand the expected behavior, but I personally find it surprising that the root logger would be modified after I pass a `logger` which isn't the root logger. I'm confused. :smile:

**Comment by WinstonJenks** [comment] 2023-04-20 04:17
I am also seeing this problem with version 15.0.6.  I use an argument, --color, to optionally turn on colored logs.  This code works for me now in a class where I have my own logger, self.log, without causing other loggers to emit messages at the DEBUG level when I set my logger to the DEBUG level.  Thanks to jacobcxdev above for tracking this down.

```
    if args.color:
        rootLogLevel = logging.getLogger().getEffectiveLevel()   # Get root logging level
        coloredlogs.install(level=self.log.getEffectiveLevel(), logger=self.log)
        logging.getLogger().setLevel(rootLogLevel)  # Restore the root logging level
```
