### ISSUE TITLE
After PIP install, ImportError: No module named coloredlogs

### ISSUE THREAD

**Issue by Patronics** [xolox/python-coloredlogs#63] opened 2018-12-18 03:44 UTC
I get this error when trying to import coloredlogs into my python program. I tried the suggestions here https://stackoverflow.com/questions/32680081/importerror-after-successful-pip-installation but they didn't help

**Comment by oleander** [comment] 2019-06-27 08:35
`python -m pip install coloredlogs` worked for me using python `2.7.16`.

**Comment by xolox** [comment] 2020-02-15 22:11
This is usually caused by confusion over which `pip` (bound to a specific Python version / installation prefix) is actually being run when `pip install ...` succeeds. The `python -m pip install ...` alternative makes it easier to avoid this confusion. I'm going to close this issue now because this has nothing to do with the `coloredlogs` package itself.

**Closed by xolox** 2020-02-15 22:11 UTC

**Comment by startergo** [comment] 2023-01-04 15:15
I got this error too regardless of installed method:
```
python -m pip install coloredlogs
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: coloredlogs in /home/g5/.local/lib/python3.10/site-packages (15.0.1)
Requirement already satisfied: humanfriendly>=9.1 in /home/g5/.local/lib/python3.10/site-packages (from coloredlogs) (10.0)
```
```
sudo ./run.sh 
python3 is /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/g5/Downloads/openairplay-master/openairplay/gui_main.py", line 6, in <module>
    from . import log
  File "/home/g5/Downloads/openairplay-master/openairplay/log.py", line 8, in <module>
    import coloredlogs
ModuleNotFoundError: No module named 'coloredlogs'
```
Managed to fix it by installing ```coloredlogs``` directly from Aur package.
Definitely  ```python -m pip install coloredlogs``` does not work.
