### ISSUE TITLE
coloredlogs cli tool issue

### ISSUE THREAD

**Issue by AlJohri** [xolox/python-coloredlogs#12] opened 2015-12-07 06:20 UTC
```
➜  workspace  coloredlogs --to-html test2.py
script: illegal option -- e
usage: script [-adkpqr] [-t time] [file [command ...]]
```

I'm getting the following error running on Mac OS X 10.11 with ZSH shell. Running without the --e flag also does something pretty weird. I think it like flushes STDOUT and then prints a bunch of blank lines. Unclear.

test2.py is as follows:

```
# Create a logger object.
import logging
logger = logging.getLogger('your-module')

# Initialize coloredlogs.
import coloredlogs
coloredlogs.install(level='DEBUG')

# Some examples.
logger.debug("this is a debugging message")
logger.info("this is an informational message")
logger.warn("this is a warning message")
logger.error("this is an error message")
logger.critical("this is a critical message")
```

straight from the examples :)

**Comment by xolox** [comment] 2015-12-14 18:23
It looks like my usage of the `script` program is using features (command line options) that aren't available in the Mac OS X version of the `script` program. I'll investigate if/how this can be improved.

**Comment by xolox** [comment] 2016-10-09 20:36
Hi again Al Johri and thanks for the feedback. Sorry this issue has been open for such a long time; I wasn't sure how to proceed without access to a Mac OS X testing environment.

Today I learned that with some effort, Travis CI can be configured to run test suites on Mac OS X. I [stumbled around in the dark](https://github.com/xolox/python-coloredlogs/compare/ae5ea86b9748014c61560d3508102c07fcb341c0...fe9c81683fa780fba54fbb63e60a0b2199df6ee7) for a while but eventually I got the Python test suite running on Mac OS X, which enabled me to [reproduce](https://travis-ci.org/xolox/python-coloredlogs/builds/166209312) the issue you reported. Then I [stumbled around in the dark again](https://github.com/xolox/python-coloredlogs/compare/fe9c81683fa780fba54fbb63e60a0b2199df6ee7...de41251e56d46e62a58ead809d6bd3b602b3d87d) trying to get the test suite to actually _pass_ on Mac OS X. Eventually I succeeded and I'm hoping that this will have resolved the problem you reported.

I'm closing this issue because I'm under the impression that the problem you reported is fixed, but if you find otherwise then please feel free to reopen this issue or open a new one.

**Closed** 2016-10-09 20:35 UTC
