### ISSUE TITLE
problems installing coloredlogs 6.0

### ISSUE THREAD

**Issue by boegel** [xolox/python-coloredlogs#26] opened 2017-03-22 13:10 UTC
I'm running into problems with getting coloredlgos 6.0 installed:

* i) `easy_install` refuses to install `coloredlogs` 6.0 because it tries to work with files outside the sandbox:

```
$ easy_install --version
setuptools 29.0.1 from /Users/kehoste/.pypkgs/lib/python2.7/site-packages/setuptools-29.0.1-py2.7.egg (Python 2.7)

$ easy_install -U --prefix ~/.pypkgs coloredlogs
Searching for coloredlogs
Reading https://pypi.python.org/simple/coloredlogs/
Downloading https://pypi.python.org/packages/fe/c1/5a1106e70b74ce51130ecace0ad52e6035f3876b973333a6f149a711c660/coloredlogs-6.0.tar.gz#md5=713e08247c3fede29c2717433c38ba71
Best match: coloredlogs 6.0
Processing coloredlogs-6.0.tar.gz
Writing /var/folders/xl/p7lmsxcs0bsg5_zv9y9lzk5c0000gn/T/easy_install-Zn0ret/coloredlogs-6.0/setup.cfg
Running coloredlogs-6.0/setup.py -q bdist_egg --dist-dir /var/folders/xl/p7lmsxcs0bsg5_zv9y9lzk5c0000gn/T/easy_install-Zn0ret/coloredlogs-6.0/egg-dist-tmp-le3AKN
error: Setup script exited with error: SandboxViolation: mkdir('/private/var/folders/xl/p7lmsxcs0bsg5_zv9y9lzk5c0000gn/Library', 511) {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.
```

* ii) When `setuptools` installs `coloredlogs` 6.0 as a dependency for my tool when running the tests with `python setup.py test` (since `coloredlogs` is listed in `tests_require`), for some reason Python start consuming *a lot* of memory (I saw it go up to 30GB) before it makes my system swap. I'm seeing this on macOS Sierra 10.12.3.

I'm not sure if ii) is related to i), maybe it's a weird side-effect?

**Comment by xolox** [comment] 2017-04-29 00:59
Hi Kenneth and thanks for the feedback.

With regards to your first point:

- Is there a specific reason why you're using `easy_install` instead of `pip`?
- Have you tried to install coloredlogs using [pip](https://pip.pypa.io/en/stable/quickstart/) instead? Do you get the same failure?
- I suppose the failure you're running into could be related to the introduction of a `.pth` file in coloredlogs 5.2 (see also #20). You could help to confirm this assumption by checking if the installation of `coloredlogs<5.2` does work for you. 
- On Linux I can't reproduce this issue - installation of coloredlogs using `easy_install` seems to work fine.

With regards to your second point:

- This may indeed be related to the installation failure in your first point, although the enormous memory usage does sound kind of absurd. A weird side-effect indeed...
- I have in the past also used the `tests_require` option but have long since switched to a `requirements-tests.txt` file that is referenced in my `Makefile` and `tox.ini` files. Also I don't use Mac OS X. This makes it hard to properly diagnose this issue.

**Comment by hugovk** [comment] 2020-02-15 05:05
No reply in 3 years, time to close the issue?

**Comment by xolox** [comment] 2020-02-15 18:09
Definitely time to close, thanks for the prod Hugo 😊.

**Closed by xolox** 2020-02-15 18:09 UTC
